name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: ./mvnw package site:jar source:jar  --file pom.xml --no-transfer-progress
    - name: Publish
      run: ./mvnw deploy -Pgithub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Setup GPG
      run: echo $GPG_KEY | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Publish package
      run: ./mvnw -B package site:jar source:jar deploy -Poss-sonatype -Dgpg.keyname=$GPG_KEY_ID -Dgpg.passphrase=$GPG_KEY_PASS
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
